/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class swl_monitor_SecEnvManager */

#ifndef _Included_swl_monitor_SecEnvManager
#define _Included_swl_monitor_SecEnvManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     swl_monitor_SecEnvManager
 * Method:    native_SecEnvOpen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_swl_monitor_SecEnvManager_native_1SecEnvOpen
  (JNIEnv *, jobject);

/*
 * Class:     swl_monitor_SecEnvManager
 * Method:    native_SecEnvClearRules
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_swl_monitor_SecEnvManager_native_1SecEnvClearRules
  (JNIEnv *, jobject, jint);

/*
 * Class:     swl_monitor_SecEnvManager
 * Method:    native_SecEnvAddRule
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_swl_monitor_SecEnvManager_native_1SecEnvAddRule
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     swl_monitor_SecEnvManager
 * Method:    native_SecEnvGetRuleNum
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_swl_monitor_SecEnvManager_native_1SecEnvGetRuleNum
  (JNIEnv *, jobject, jint);

/*
 * Class:     swl_monitor_SecEnvManager
 * Method:    native_SecEnvGetNthRule
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_swl_monitor_SecEnvManager_native_1SecEnvGetNthRule
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     swl_monitor_SecEnvManager
 * Method:    native_SecEnvClose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_swl_monitor_SecEnvManager_native_1SecEnvClose
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
